### ISSUE TITLE
Extension causes Reddit comments to be rendered with Times New Roman

### ISSUE THREAD

**Issue by pandaninjas** [matthijs110/chromium-country-flags#2]
**Describe the bug**
When using the extension on Reddit, `font-family` becomes `"Twemoji Country Flags", "Times New Roman"`.
Without the extension, `font-family` is `-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", sans-serif`
**To Reproduce**
Go to Reddit
Look at the CSS in the inspector
**Chrome version:**
`124.0.6367.119`
**Additional context**
N/A

**Comment by matthijs110** [comment]
Hi @pandaninjas, I am not able to reproduce this issue. Do you have a link for me where this happens?

**Comment by pandaninjas** [comment]
> Hi @pandaninjas, I am not able to reproduce this issue. Do you have a link for me where this happens?

It's a bit unreliable but once it starts happening it keeps happening until the extension is reloaded.

**Comment by matthijs110** [comment]
Sorry for the wait, but I have been able to reproduce the issue thanks to a friend of mine :) We have been working on a new approach and I hope to release it soon!
