### ISSUE TITLE
Extension replacing esential fonts in some websites

### ISSUE THREAD

**Issue by javierbentez** [matthijs110/chromium-country-flags#4]
**Describe the bug**
Hi! After upgrading to version 2.0, the new extension css is replacing the font family of Expo Vector Icons.

**To Reproduce**
You can see this error going to the library official website: https://icons.expo.fyi/Index

**Screenshots**
![image](https://github.com/matthijs110/chromium-country-flags/assets/74602848/01494f35-b925-4f68-bbaa-cdf65b76aa41)

**Chrome version:**
125.0.6422.142

**Additional context**
If I disable the new css extension rule, the icons are loaded perfectly again

**Comment by matthijs110** [comment]
Hi @javierbentez Thanks for reporting this issue. I was able to reproduce it and I am working on a solution :)

**Comment by matthijs110** [comment]
Hi @javierbentez I have implemented and tested the solution. It's now under review at Google and should be available to you soon! :)
